{
 "title": "Home Lab Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "VM Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 1, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance_name)(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " RAM Usage %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Container Memory",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(docker_container_mem_usage{container_name!~\"prometheus|grafana|telegraf|node-exporter\"})",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Container CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent{container_name!~\"prometheus|grafana|telegraf|node-exporter\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Container CPU %",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(docker_container_cpu_usage_percent{container_name!~\"prometheus|grafana|telegraf|node-exporter\"})",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Top 5 Memory",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container_name) (docker_container_mem_usage)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Container Restarts (24h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "changes(docker_container_status{container_name!~\"prometheus|grafana|telegraf|node-exporter\", container_status=\"running\"}[24h]) > 0",
     "legendFormat": "{{container_name}}"
    }
   ]
  }
 ]
}