[agent]
  interval = "30s"

[[outputs.prometheus_client]]
  listen = ":9273"

[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  gather_services = false
  container_names = []
  perdevice = false
  total = true
